"""empty message

Revision ID: 05fb84947e66
Revises: 1755854bacbc
Create Date: 2019-09-25 08:54:03.221782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05fb84947e66'
down_revision = '1755854bacbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('category_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news', 'category_id')
    # ### end Alembic commands ###
