"""empty message

Revision ID: 0744b9ab7570
Revises: 61c20172328d
Create Date: 2019-09-23 17:53:55.490156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0744b9ab7570'
down_revision = '61c20172328d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'cms_user', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cms_user', type_='unique')
    # ### end Alembic commands ###
