"""empty message

Revision ID: 1755854bacbc
Revises: 0744b9ab7570
Create Date: 2019-09-24 08:37:12.479437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1755854bacbc'
down_revision = '0744b9ab7570'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('status', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news', 'status')
    # ### end Alembic commands ###
