"""empty message

Revision ID: 61c20172328d
Revises: 722e9773617a
Create Date: 2019-09-23 17:02:36.602301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61c20172328d'
down_revision = '722e9773617a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('new_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comment', 'news', ['new_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_column('comment', 'new_id')
    # ### end Alembic commands ###
