"""empty message

Revision ID: 63cfe13ea853
Revises: 7507ec91ff79
Create Date: 2019-09-17 20:09:00.445338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63cfe13ea853'
down_revision = '7507ec91ff79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('source', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news', 'source')
    # ### end Alembic commands ###
