"""empty message

Revision ID: 7507ec91ff79
Revises: f4684ea879ae
Create Date: 2019-09-17 20:00:48.627381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7507ec91ff79'
down_revision = 'f4684ea879ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('author', sa.String(length=50), nullable=True),
    sa.Column('send_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('news')
    # ### end Alembic commands ###
