"""empty message

Revision ID: 9dd18762d796
Revises: 63cfe13ea853
Create Date: 2019-09-18 19:20:54.236217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dd18762d796'
down_revision = '63cfe13ea853'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('digest', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news', 'digest')
    # ### end Alembic commands ###
