"""empty message

Revision ID: f4684ea879ae
Revises: 586f2975d110
Create Date: 2019-09-14 23:37:56.075689

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f4684ea879ae'
down_revision = '586f2975d110'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cms_user', sa.Column('password', sa.String(length=100), nullable=False))
    op.drop_column('cms_user', '_password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cms_user', sa.Column('_password', mysql.VARCHAR(length=100), nullable=False))
    op.drop_column('cms_user', 'password')
    # ### end Alembic commands ###
